// generated by stringer -type=Level; DO NOT EDIT

package logger

import "fmt"

const (
	_Level_name_0 = "LevelTraceOnlyLevelInfoOnly"
	_Level_name_1 = "LevelWarningOnly"
	_Level_name_2 = "LevelErrorOnly"
)

var (
	_Level_index_0 = [...]uint8{0, 14, 27}
	_Level_index_1 = [...]uint8{0, 16}
	_Level_index_2 = [...]uint8{0, 14}
)

func (i Level) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Level_name_0[_Level_index_0[i]:_Level_index_0[i+1]]
	case i == 4:
		return _Level_name_1
	case i == 8:
		return _Level_name_2
	default:
		return fmt.Sprintf("Level(%d)", i)
	}
}
